### PR TITLE
Update deprecated parameters

### LINKED ISSUE #6: Remove usage of deprecated parameters
In https://github.com/projectsyn/commodore/pull/192, some parameter values were deprecated. This component is affected by this change and needs to adapt. See the commodore change log for the details.

### PR DESCRIPTION
**Pull request by srueg**
Closes #6

## Checklist

- [x] keep pull requests small so they can be easily reviewed
- [x] update ./CHANGELOG.md
- [x] link this PR to related issues

### CODE REVIEW

**Review by corvus-ch — APPROVED** [review]

**Comment by mweibel** [comment]
For some reason I still need to investigate, this seems to have broken the projectsyn quickstart (step [`Run Commodore`](https://syn.tools/syn/tutorials/getting-started.html#_run_commodore)):

```
commodore@commodore-shell:~$ commodore catalog compile $CLUSTER_ID --push
Cleaning working tree
Updating global config...
Updating customer config...
Discovering components...
Fetching components...
Updating Kapitan target...
Updating cluster catalog...
 > Reference at 'refs/heads/master' does not exist, creating initial commit for catalog
Updating Jsonnet libraries...
Cleaning catalog repository...
 > Converting old-style catalog
Updating Kapitan secret references...
Compiling catalog...


Jsonnet error: failed to compile ./dependencies/argocd/component/redis.jsonnet:
 RUNTIME ERROR: field does not exist: facts
        ./dependencies/argocd/component/redis.jsonnet:14:30-50  thunk <a>
        std.jsonnet:46:19
        std.jsonnet:46:8-21     function <anonymous>
        ./dependencies/argocd/component/redis.jsonnet:14:15-77  object <anonymous>
        ./dependencies/argocd/component/redis.jsonnet:(11:12)-(30:6)    object <anonymous>
        ./dependencies/argocd/component/redis.jsonnet:(10:14)-(31:4)    object <anonymous>
        ./dependencies/argocd/component/redis.jsonnet:(35:1)-(42:2)     object <anonymous>
        During manifestation

Compile error: failed to compile target: cluster
```

**Comment by srueg** [comment]
You're absolutely right. @tobru can you update the getting started to `v0.3.0`?

@mweibel in the meantime can you please give it a try by using the latest release of commodore?
`--image=docker.io/projectsyn/commodore:v0.3.0`

**Comment by mweibel** [comment]
@srueg thanks for the quick reply. 

Not sure if I should open a new issue, but using `v0.3.0` gave me another error:
```
commodore@commodore-shell:~$ commodore catalog compile $CLUSTER_ID --push
Cleaning working tree
Updating Kapitan target...
Updating cluster parameters...
Updating global config...
Updating customer config...
Discovering components...
Fetching components...
Updating Kapitan target...
Updating cluster catalog...
 > Reference at 'refs/heads/master' does not exist, creating initial commit for catalog
LOCAL lib -> /app/dependencies/lib
Cleaning catalog repository...
 > Converting old-style catalog
Updating Kapitan secret references...
Traceback (most recent call last):
  File "/usr/local/bin/commodore", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/commodore/cli.py", line 174, in main
    commodore.main(prog_name='commodore', auto_envvar_prefix='COMMODORE')
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/commodore/cli.py", line 85, in compile_catalog
    _compile(config, cluster)
  File "/usr/local/lib/python3.8/site-packages/commodore/compile.py", line 162, in compile
    update_refs(config, kapitan_inventory['parameters'])
  File "/usr/local/lib/python3.8/site-packages/commodore/refs.py", line 172, in update_refs
    ref_params = rb.params
  File "/usr/local/lib/python3.8/site-packages/commodore/refs.py", line 150, in params
    kapitan_params = self.parameters['kapitan']['secrets']['vaultkv']
KeyError: 'kapitan'
```

**Comment by srueg** [comment]
Can you try to run the other commands which are referencing `v0.2.0` again with `v0.3.0`?

**Comment by srueg** [comment]
With https://github.com/projectsyn/commodore-defaults/pull/2 merged, the current tutorial should now work again (with version `v0.2.0`).

**Comment by mweibel** [comment]
great 👍 yep that works. Just changing to `v0.3.0` didn't work. I assume other changes would've been needed then :)

**Pull request merged**
